version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpg_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - uploads_data:/app/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rpg-backend.rule=Host(`api.dailydev.com.br`)"
      - "traefik.http.routers.rpg-backend.entrypoints=web,websecure"
      - "traefik.http.routers.rpg-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.rpg-backend.loadbalancer.server.port=3001"
    networks:
      - web

volumes:
  uploads_data:

networks:
  web:
    external: true
